services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: node-server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - node_modules:/app/node_modules
      - ./server/uploads:/app/uploads
    env_file:
      - ./server/.env
    depends_on:
      - postgres
    networks:
      - webnet

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: next-client
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      - NEXT_PUBLIC_API_URL=https://api.arnaudies-lilian.work


  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webnet


volumes:
  postgres_data:
  node_modules:

networks:
  webnet:
    driver: bridge
